name: delete dev tag
on:
  pull_request:
    types: [ closed ]

env:
  DEV_TAG: dev.${{ github.head_ref }}

jobs:
  delete-dev-tag:
    runs-on: ubuntu-latest # [self-hosted, Linux, X64, gcp, small]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Config Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: delete dev tag reference
        run: |
          git push --delete origin ${{ env.DEV_TAG }}
