name: Manual Release for tag
on:
  workflow_dispatch:
    inputs:
      source-tag:
        type: string
        description: the source branch or tag that the new release will be created from
        required: true

      target-tag:
        type: string
        description: the new tag created from the source
        required: true

jobs:
  tag-and-release:
    runs-on: ubuntu-20.04 # [self-hosted, Linux, X64, gcp, small]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      POST_RELEASE_TAG_NAME: latest

    steps:
      - uses: actions/checkout@v3

      - name: Get source tag SHA
        run: |
          git fetch --all --tags
          git checkout ${{ inputs.source-tag }}
          echo "SOURCE_TAG_SHA=$(git rev-parse --verify HEAD)" >> $GITHUB_ENV

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ inputs.target-tag }}
          release_name: Release ${{ inputs.target-tag }} from tag ${{ inputs.source-tag }}
          commitish: ${{ env.SOURCE_TAG_SHA }}
          body: ${{ needs.generate-changelog.outputs.changelog }}

  generate-moving-tag:
    uses: ./.github/workflows/generate-moving-tag.yml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      tag_name: latest
      release_name: ${{ inputs.source-tag }}
