name: Verify code style
on:
  pull_request:
  workflow_call:
    secrets:
        SSH_REPO_ACCESS:
          required: false

jobs:
  verify-code-style:
    runs-on: ubuntu-latest # TODO: [self-hosted, Linux, X64, gcp, small]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # - uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_REPO_ACCESS }}
# 
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: verify-cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      # - name: Verify code style - JS
      # run: npm run lint:eslint --if-present

      - name: Verify code style - HTML & CSS
        run: npm run prettier:check --if-present
